#!/usr/bin/env lua

local function script_path()
    local str = debug.getinfo(2, "S").source:sub(2)
    return str:match("(.*/)")
end

local config_path = script_path()

package.cpath = string.format("%s;/Users/%s/.local/share/sketchybar_lua/?.so", package.cpath, os.getenv("USER"))
package.path = string.format("%s;%s/?.lua;%s/?/init.lua", package.path, config_path, config_path)

_G.sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()

sbar.event_loop()
